services:
  backend:
    image: backend-image
    build:
     context: ./backend
     dockerfile: Dockerfile
    container_name: container-backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  frontend:
    image: frontend-image
    build:
     context: ./frontend
     dockerfile: Dockerfile
    container_name: container-frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    networks:
      - frontend   

  mongo:
    image: mongo:6
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=secret   

volumes:
  mongo-data:
networks:
  frontend:
  backend:



    